#!/usr/bin/env node
// Regenerates scripts/schema.sql from the live (or local) D1 schema, so the
// repository always has one canonical, deterministic source of truth instead of
// a hand-maintained init-db.sql that drifts from the migration chain.
//
// Usage:
//   node scripts/export-schema.mjs            # --remote
//   D1_DATABASE=audioroom-db node scripts/export-schema.mjs
//   D1_REMOTE=0 node scripts/export-schema.mjs   # local Miniflare D1
import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const db = (process.env.D1_DATABASE ?? "audioroom-db").trim();
if (!/^[A-Za-z0-9_-]{1,64}$/.test(db)) {
  console.error(`D1_DATABASE "${db}" is not a valid database name.`);
  process.exit(1);
}
const remote = process.env.D1_REMOTE !== "0";

const query = `
SELECT type, name, sql FROM sqlite_master
WHERE sql IS NOT NULL
  AND name NOT LIKE 'sqlite_%'
  AND name NOT LIKE 'd1_%'
ORDER BY
  CASE type WHEN 'table' THEN 0 WHEN 'index' THEN 1 WHEN 'trigger' THEN 2 WHEN 'view' THEN 3 ELSE 4 END,
  name;
`;

const npx = process.platform === "win32" ? "npx.cmd" : "npx";
const args = ["wrangler", "d1", "execute", db, "--command", query, "--json"];
if (remote) args.push("--remote");

const raw = execFileSync(npx, args, { encoding: "utf8", maxBuffer: 64 * 1024 * 1024 });
const parsed = JSON.parse(raw);
// `wrangler d1 execute --json` returns an array of statement results; a SELECT
// statement's results are objects keyed by column name.
const rows = Array.isArray(parsed) ? parsed.flatMap((r) => r?.results ?? []) : [];
if (!rows.length) {
  console.error("No schema objects returned — check D1_DATABASE and credentials.");
  process.exit(1);
}

const out = [
  "-- Canonical D1 schema — generated by `npm run db:export`. DO NOT EDIT BY HAND.",
  `-- Source: database "${db}"${remote ? " (remote)" : " (local)"}.`,
  "-- Regenerate after any migration and commit the diff so drift is visible in review.",
  "",
  "PRAGMA foreign_keys = ON;",
  "",
  ...rows.map((r) => `${r.sql};`),
  "",
].join("\n");

const dest = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "schema.sql");
writeFileSync(dest, out, "utf8");
console.log(`Wrote ${rows.length} schema objects to ${dest}`);
